version: '3.8'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./DjangoRed
    # Запускаем тестовый сервер
    command: gunicorn DjangoRed.wsgi:application --bind 0.0.0.0:8000
    # куда будут помещены данные из каталога app
    volumes:
      - ./DjangoRed/:/usr/src/DjangoRed/
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    ports:
     - 1337:80
    depends_on:
     - web
