version: '3.0'

services:
  backend:
    build: ./DjangoRed
    command:  sh -c "daphne -b 0.0.0.0 -p 8000 DjangoRed.asgi:application & python ./DjangoRed/manage.py makemigrations & python ./DjangoRed/manage.py migrate & celery -A DjangoRed worker --loglevel=INFO"
    expose:
      - "8000"
    volumes:
     - ./DjangoRed/static/:/static/
    links:
     - 'mysqlred'
     - 'message-broker'
  nginx:
    build: ./nginx
    ports:
     - 80:80
    command: ""
    healthcheck:
        test: ["CMD", "curl", "-fk", "http://localhost:8000"]
        interval: 5s
        timeout: 6s
        retries: 10
    environment:
      - NGINX_HOST=51.250.112.4
      - NGINX_PORT=80
      - DAPHNE_HOST=backend
      - DAPHNE_PORT=8000
    volumes:
      - ./DjangoRed/static/:/static/
  message-broker:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  mysqlred:
    build: ./MySQL
    ports:
      - 3307:3306
    command: --lower_case_table_names=1
    volumes:
      - /var/lib/mysql

