version: '3.8'
services:

  backend:
    build: ./DjangoRed
    command:  sh -c "daphne -b 0.0.0.0 -p 8000 DjangoRed.asgi:application & python ./DjangoRed/manage.py makemigrations & python manage.py createsuperuser --noinput --username Vasilenich --email Vasilenich@bezd.com --password Vasilenich &  celery -A DjangoRed worker --loglevel=INFO"
    expose:
      - "8000"
    volumes:
     - ./DjangoRed/static/:/static/
    links:
     - 'mysqlred'
     - 'message-broker'
  nginx:
    image: shizvizor/nginxsec:latest
    restart: unless-stopped
    ports:
      - 80:80
    command: ""
    healthcheck:
      test: [ "CMD", "curl", "-fk", "http://localhost:8000" ]
      interval: 5s
      timeout: 6s
      retries: 10
    environment:
      - NGINX_HOST=51.250.112.4
      - NGINX_PORT=80
      - DAPHNE_HOST=backend
      - DAPHNE_PORT=8000
    volumes:
      - ./DjangoRed/static/:/static/
      - ./appsec-logs:/ext/appsec-logs
      - ./appsec-localconfig:/ext/appsec

  appsec-agent:
    container_name: open-appsec-agent
    image: 'ghcr.io/openappsec/agent:latest'
    network_mode: service:nginx
    ipc: host
    restart: unless-stopped
    environment:
      - nginx=true
      - autoPolicyLoad=true
    volumes:
      - ./appsec-config:/etc/cp/conf
      - ./appsec-data:/etc/cp/data
      - ./appsec-logs:/var/log/nano_agent
      - ./appsec-localconfig:/ext/appsec
    command: /cp-nano-agent --standalone

  message-broker:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  mysqlred:
    build: ./MySQL
    ports:
      - 3307:3306
    command: --lower_case_table_names=1
    volumes:
      - /var/lib/mysql