version: '3.8'
networks:
  backnet:
services:
#  web:
#    image: shizvizor/reddjango
#    command: gunicorn DjangoRed.asgi:application --bind 0.0.0.0:8000
#    volumes:
#      - ./DjangoRed/:/usr/src/DjangoRed/
#    ports:
#      - 8000:8000
#    env_file:
#      - ./.env.dev
  nginx:
    build: ./nginx
    ports:
     - 1337:80
  message-broker:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  mysqlRed:
    image: shizvizor/redmysql
    ports:
      - 8001:3306
    command: --lower_case_table_names=1