# Generated by Django 4.2.11 on 2024-05-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0004_alter_useraccount_options_alter_useraccount_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_of_birth',
        ),
    ]
