# Generated by Django 4.2.11 on 2024-05-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0005_remove_useraccount_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='BaseUserName', max_length=32, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
