# Generated by Django 4.2.11 on 2024-05-19 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0009_favoritejobids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritejobids',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
