# Generated by Django 4.2.11 on 2024-05-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0010_alter_favoritejobids_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='username'),
        ),
    ]
