# Generated by Django 4.2.11 on 2024-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0013_remove_useraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
    ]
