user: clusterizer
password: 5AP@32%/VtDo_J+9
database: reddit_parsing
database_cluster: reddit_clustering
port: 3306 # during development change to 3309
# during development change to localhost
host: mysqlred #
